/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddObjectRequest from './model/AddObjectRequest';
import Animation from './model/Animation';
import ArchiveNested from './model/ArchiveNested';
import AttachRequest from './model/AttachRequest';
import AvatarRelated from './model/AvatarRelated';
import CapabilitiesAndConfig from './model/CapabilitiesAndConfig';
import Client from './model/Client';
import Content from './model/Content';
import ContentCategory from './model/ContentCategory';
import CreateWorldOptions from './model/CreateWorldOptions';
import Cursors from './model/Cursors';
import GltfModel from './model/GltfModel';
import GroupMember from './model/GroupMember';
import GroupMessage from './model/GroupMessage';
import ImageInfo from './model/ImageInfo';
import InlineArchives from './model/InlineArchives';
import LoginResponse from './model/LoginResponse';
import ModelCategory from './model/ModelCategory';
import ModelLicense from './model/ModelLicense';
import ModelSearchList from './model/ModelSearchList';
import ModelSearchRequest from './model/ModelSearchRequest';
import ModelSearchResponse from './model/ModelSearchResponse';
import ModelTag from './model/ModelTag';
import PersistentEvent from './model/PersistentEvent';
import Point from './model/Point';
import Quaternion from './model/Quaternion';
import Recording from './model/Recording';
import RecordingData from './model/RecordingData';
import RecordingStateParameter from './model/RecordingStateParameter';
import Rotation from './model/Rotation';
import SceneProperties from './model/SceneProperties';
import ServerCapabilities from './model/ServerCapabilities';
import ServerConfiguration from './model/ServerConfiguration';
import ThumbnailsRelated from './model/ThumbnailsRelated';
import User from './model/User';
import UserData from './model/UserData';
import UserGroup from './model/UserGroup';
import UserRelated from './model/UserRelated';
import VRObject from './model/VRObject';
import Welcome from './model/Welcome';
import WelcomeWelcome from './model/WelcomeWelcome';
import World from './model/World';
import WorldStatus from './model/WorldStatus';
import DataApi from './api/DataApi';
import GroupsApi from './api/GroupsApi';
import Oauth2LoginApi from './api/Oauth2LoginApi';
import RecorderApi from './api/RecorderApi';
import ServerInfoApi from './api/ServerInfoApi';
import SharedContentApi from './api/SharedContentApi';
import SketchfabApi from './api/SketchfabApi';
import TexturesApi from './api/TexturesApi';
import UsersApi from './api/UsersApi';
import WorldObjectsApi from './api/WorldObjectsApi';
import WorldsApi from './api/WorldsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddObjectRequest model constructor.
     * @property {AddObjectRequest}
     */
    AddObjectRequest,

    /**
     * The Animation model constructor.
     * @property {Animation}
     */
    Animation,

    /**
     * The ArchiveNested model constructor.
     * @property {ArchiveNested}
     */
    ArchiveNested,

    /**
     * The AttachRequest model constructor.
     * @property {AttachRequest}
     */
    AttachRequest,

    /**
     * The AvatarRelated model constructor.
     * @property {AvatarRelated}
     */
    AvatarRelated,

    /**
     * The CapabilitiesAndConfig model constructor.
     * @property {CapabilitiesAndConfig}
     */
    CapabilitiesAndConfig,

    /**
     * The Client model constructor.
     * @property {Client}
     */
    Client,

    /**
     * The Content model constructor.
     * @property {Content}
     */
    Content,

    /**
     * The ContentCategory model constructor.
     * @property {ContentCategory}
     */
    ContentCategory,

    /**
     * The CreateWorldOptions model constructor.
     * @property {CreateWorldOptions}
     */
    CreateWorldOptions,

    /**
     * The Cursors model constructor.
     * @property {Cursors}
     */
    Cursors,

    /**
     * The GltfModel model constructor.
     * @property {GltfModel}
     */
    GltfModel,

    /**
     * The GroupMember model constructor.
     * @property {GroupMember}
     */
    GroupMember,

    /**
     * The GroupMessage model constructor.
     * @property {GroupMessage}
     */
    GroupMessage,

    /**
     * The ImageInfo model constructor.
     * @property {ImageInfo}
     */
    ImageInfo,

    /**
     * The InlineArchives model constructor.
     * @property {InlineArchives}
     */
    InlineArchives,

    /**
     * The LoginResponse model constructor.
     * @property {LoginResponse}
     */
    LoginResponse,

    /**
     * The ModelCategory model constructor.
     * @property {ModelCategory}
     */
    ModelCategory,

    /**
     * The ModelLicense model constructor.
     * @property {ModelLicense}
     */
    ModelLicense,

    /**
     * The ModelSearchList model constructor.
     * @property {ModelSearchList}
     */
    ModelSearchList,

    /**
     * The ModelSearchRequest model constructor.
     * @property {ModelSearchRequest}
     */
    ModelSearchRequest,

    /**
     * The ModelSearchResponse model constructor.
     * @property {ModelSearchResponse}
     */
    ModelSearchResponse,

    /**
     * The ModelTag model constructor.
     * @property {ModelTag}
     */
    ModelTag,

    /**
     * The PersistentEvent model constructor.
     * @property {PersistentEvent}
     */
    PersistentEvent,

    /**
     * The Point model constructor.
     * @property {Point}
     */
    Point,

    /**
     * The Quaternion model constructor.
     * @property {Quaternion}
     */
    Quaternion,

    /**
     * The Recording model constructor.
     * @property {Recording}
     */
    Recording,

    /**
     * The RecordingData model constructor.
     * @property {RecordingData}
     */
    RecordingData,

    /**
     * The RecordingStateParameter model constructor.
     * @property {RecordingStateParameter}
     */
    RecordingStateParameter,

    /**
     * The Rotation model constructor.
     * @property {Rotation}
     */
    Rotation,

    /**
     * The SceneProperties model constructor.
     * @property {SceneProperties}
     */
    SceneProperties,

    /**
     * The ServerCapabilities model constructor.
     * @property {ServerCapabilities}
     */
    ServerCapabilities,

    /**
     * The ServerConfiguration model constructor.
     * @property {ServerConfiguration}
     */
    ServerConfiguration,

    /**
     * The ThumbnailsRelated model constructor.
     * @property {ThumbnailsRelated}
     */
    ThumbnailsRelated,

    /**
     * The User model constructor.
     * @property {User}
     */
    User,

    /**
     * The UserData model constructor.
     * @property {UserData}
     */
    UserData,

    /**
     * The UserGroup model constructor.
     * @property {UserGroup}
     */
    UserGroup,

    /**
     * The UserRelated model constructor.
     * @property {UserRelated}
     */
    UserRelated,

    /**
     * The VRObject model constructor.
     * @property {VRObject}
     */
    VRObject,

    /**
     * The Welcome model constructor.
     * @property {Welcome}
     */
    Welcome,

    /**
     * The WelcomeWelcome model constructor.
     * @property {WelcomeWelcome}
     */
    WelcomeWelcome,

    /**
     * The World model constructor.
     * @property {World}
     */
    World,

    /**
     * The WorldStatus model constructor.
     * @property {WorldStatus}
     */
    WorldStatus,

    /**
    * The DataApi service constructor.
    * @property {module:api/DataApi}
    */
    DataApi,

    /**
    * The GroupsApi service constructor.
    * @property {module:api/GroupsApi}
    */
    GroupsApi,

    /**
    * The Oauth2LoginApi service constructor.
    * @property {module:api/Oauth2LoginApi}
    */
    Oauth2LoginApi,

    /**
    * The RecorderApi service constructor.
    * @property {module:api/RecorderApi}
    */
    RecorderApi,

    /**
    * The ServerInfoApi service constructor.
    * @property {module:api/ServerInfoApi}
    */
    ServerInfoApi,

    /**
    * The SharedContentApi service constructor.
    * @property {module:api/SharedContentApi}
    */
    SharedContentApi,

    /**
    * The SketchfabApi service constructor.
    * @property {module:api/SketchfabApi}
    */
    SketchfabApi,

    /**
    * The TexturesApi service constructor.
    * @property {module:api/TexturesApi}
    */
    TexturesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WorldObjectsApi service constructor.
    * @property {module:api/WorldObjectsApi}
    */
    WorldObjectsApi,

    /**
    * The WorldsApi service constructor.
    * @property {module:api/WorldsApi}
    */
    WorldsApi
};
