/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Animation from './model/Animation';
import Client from './model/Client';
import ContentCategory from './model/ContentCategory';
import CreateWorldOptions from './model/CreateWorldOptions';
import GltfModel from './model/GltfModel';
import GroupMember from './model/GroupMember';
import GroupMessage from './model/GroupMessage';
import LoginResponse from './model/LoginResponse';
import Point from './model/Point';
import Quaternion from './model/Quaternion';
import Rotation from './model/Rotation';
import SceneProperties from './model/SceneProperties';
import UploadRequest from './model/UploadRequest';
import User from './model/User';
import UserData from './model/UserData';
import UserGroup from './model/UserGroup';
import VRObject from './model/VRObject';
import WebPushSubscription from './model/WebPushSubscription';
import World from './model/World';
import WorldStatus from './model/WorldStatus';
import DataApi from './api/DataApi';
import GroupsApi from './api/GroupsApi';
import Oauth2LoginApi from './api/Oauth2LoginApi';
import RemoteBrowserApi from './api/RemoteBrowserApi';
import SharedContentApi from './api/SharedContentApi';
import SketchfabApi from './api/SketchfabApi';
import TexturesApi from './api/TexturesApi';
import UsersApi from './api/UsersApi';
import WebPushApi from './api/WebPushApi';
import WorldsApi from './api/WorldsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Animation model constructor.
     * @property {Animation}
     */
    Animation,

    /**
     * The Client model constructor.
     * @property {Client}
     */
    Client,

    /**
     * The ContentCategory model constructor.
     * @property {ContentCategory}
     */
    ContentCategory,

    /**
     * The CreateWorldOptions model constructor.
     * @property {CreateWorldOptions}
     */
    CreateWorldOptions,

    /**
     * The GltfModel model constructor.
     * @property {GltfModel}
     */
    GltfModel,

    /**
     * The GroupMember model constructor.
     * @property {GroupMember}
     */
    GroupMember,

    /**
     * The GroupMessage model constructor.
     * @property {GroupMessage}
     */
    GroupMessage,

    /**
     * The LoginResponse model constructor.
     * @property {LoginResponse}
     */
    LoginResponse,

    /**
     * The Point model constructor.
     * @property {Point}
     */
    Point,

    /**
     * The Quaternion model constructor.
     * @property {Quaternion}
     */
    Quaternion,

    /**
     * The Rotation model constructor.
     * @property {Rotation}
     */
    Rotation,

    /**
     * The SceneProperties model constructor.
     * @property {SceneProperties}
     */
    SceneProperties,

    /**
     * The UploadRequest model constructor.
     * @property {UploadRequest}
     */
    UploadRequest,

    /**
     * The User model constructor.
     * @property {User}
     */
    User,

    /**
     * The UserData model constructor.
     * @property {UserData}
     */
    UserData,

    /**
     * The UserGroup model constructor.
     * @property {UserGroup}
     */
    UserGroup,

    /**
     * The VRObject model constructor.
     * @property {VRObject}
     */
    VRObject,

    /**
     * The WebPushSubscription model constructor.
     * @property {WebPushSubscription}
     */
    WebPushSubscription,

    /**
     * The World model constructor.
     * @property {World}
     */
    World,

    /**
     * The WorldStatus model constructor.
     * @property {WorldStatus}
     */
    WorldStatus,

    /**
    * The DataApi service constructor.
    * @property {module:api/DataApi}
    */
    DataApi,

    /**
    * The GroupsApi service constructor.
    * @property {module:api/GroupsApi}
    */
    GroupsApi,

    /**
    * The Oauth2LoginApi service constructor.
    * @property {module:api/Oauth2LoginApi}
    */
    Oauth2LoginApi,

    /**
    * The RemoteBrowserApi service constructor.
    * @property {module:api/RemoteBrowserApi}
    */
    RemoteBrowserApi,

    /**
    * The SharedContentApi service constructor.
    * @property {module:api/SharedContentApi}
    */
    SharedContentApi,

    /**
    * The SketchfabApi service constructor.
    * @property {module:api/SketchfabApi}
    */
    SketchfabApi,

    /**
    * The TexturesApi service constructor.
    * @property {module:api/TexturesApi}
    */
    TexturesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WebPushApi service constructor.
    * @property {module:api/WebPushApi}
    */
    WebPushApi,

    /**
    * The WorldsApi service constructor.
    * @property {module:api/WorldsApi}
    */
    WorldsApi
};
