/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import { VRObject } from './VRObject.js';

/**
 * The AddObjectRequest model module.
 * @module model/AddObjectRequest
 * @version v0
 */
export class AddObjectRequest {
    /**
     * Constructs a new <code>AddObjectRequest</code>.
     * @alias AddObjectRequest
     */
    constructor() { 
        
        
        /** VRObject 
         * @type {VRObject} 
         */
        this.VRObject = undefined;
        
        
        
        
        AddObjectRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddObjectRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {AddObjectRequest} obj Optional instance to populate.
     * @return {AddObjectRequest} The populated <code>AddObjectRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddObjectRequest();

            if (data.hasOwnProperty('VRObject')) {
                obj['VRObject'] = VRObject.constructFromObject(data['VRObject']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddObjectRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddObjectRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `VRObject`
        if (data['VRObject']) { // data not null
          VRObject.validateJSON(data['VRObject']);
        }

        return true;
    }


}





export default AddObjectRequest;

