/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import { ServerCapabilities } from './ServerCapabilities.js';
import { ServerConfiguration } from './ServerConfiguration.js';

/**
 * The CapabilitiesAndConfig model module.
 * @module model/CapabilitiesAndConfig
 * @version v0
 */
export class CapabilitiesAndConfig {
    /**
     * Constructs a new <code>CapabilitiesAndConfig</code>.
     * @alias CapabilitiesAndConfig
     */
    constructor() { 
        
        CapabilitiesAndConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CapabilitiesAndConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {CapabilitiesAndConfig} obj Optional instance to populate.
     * @return {CapabilitiesAndConfig} The populated <code>CapabilitiesAndConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CapabilitiesAndConfig();

            if (data.hasOwnProperty('capabilities')) {
                obj['capabilities'] = ServerCapabilities.constructFromObject(data['capabilities']);
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ServerConfiguration.constructFromObject(data['config']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CapabilitiesAndConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CapabilitiesAndConfig</code>.
     */
    static validateJSON(data) {
        // validate the optional field `capabilities`
        if (data['capabilities']) { // data not null
          ServerCapabilities.validateJSON(data['capabilities']);
        }
        // validate the optional field `config`
        if (data['config']) { // data not null
          ServerConfiguration.validateJSON(data['config']);
        }

        return true;
    }


}



/**
 * @member {ServerCapabilities} capabilities
 */
CapabilitiesAndConfig.prototype['capabilities'] = undefined;

/**
 * @member {ServerConfiguration} config
 */
CapabilitiesAndConfig.prototype['config'] = undefined;






export default CapabilitiesAndConfig;

