/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import { ArchiveNested } from './ArchiveNested.js';

/**
 * The InlineArchives model module.
 * @module model/InlineArchives
 * @version v0
 */
export class InlineArchives {
    /**
     * Constructs a new <code>InlineArchives</code>.
     * @alias InlineArchives
     */
    constructor() { 
        
        
        /** glb 
         * @type {ArchiveNested} 
         */
        this.glb = undefined;

        /** gltf 
         * @type {ArchiveNested} 
         */
        this.gltf = undefined;

        /** source 
         * @type {ArchiveNested} 
         */
        this.source = undefined;

        /** usdz 
         * @type {ArchiveNested} 
         */
        this.usdz = undefined;
        
        
        
        
        InlineArchives.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineArchives</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {InlineArchives} obj Optional instance to populate.
     * @return {InlineArchives} The populated <code>InlineArchives</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineArchives();

            if (data.hasOwnProperty('glb')) {
                obj['glb'] = ArchiveNested.constructFromObject(data['glb']);
            }
            if (data.hasOwnProperty('gltf')) {
                obj['gltf'] = ArchiveNested.constructFromObject(data['gltf']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ArchiveNested.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('usdz')) {
                obj['usdz'] = ArchiveNested.constructFromObject(data['usdz']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InlineArchives</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InlineArchives</code>.
     */
    static validateJSON(data) {
        // validate the optional field `glb`
        if (data['glb']) { // data not null
          ArchiveNested.validateJSON(data['glb']);
        }
        // validate the optional field `gltf`
        if (data['gltf']) { // data not null
          ArchiveNested.validateJSON(data['gltf']);
        }
        // validate the optional field `source`
        if (data['source']) { // data not null
          ArchiveNested.validateJSON(data['source']);
        }
        // validate the optional field `usdz`
        if (data['usdz']) { // data not null
          ArchiveNested.validateJSON(data['usdz']);
        }

        return true;
    }


}





export default InlineArchives;

