/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import { Recording } from './Recording.js';

/**
 * The RecordingStateParameter model module.
 * @module model/RecordingStateParameter
 * @version v0
 */
export class RecordingStateParameter {
    /**
     * Constructs a new <code>RecordingStateParameter</code>.
     * @alias RecordingStateParameter
     */
    constructor() { 
        
        
        /** Recording 
         * @type {Recording} 
         */
        this.Recording = undefined;
        
        
        
        
        RecordingStateParameter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecordingStateParameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {RecordingStateParameter} obj Optional instance to populate.
     * @return {RecordingStateParameter} The populated <code>RecordingStateParameter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecordingStateParameter();

            if (data.hasOwnProperty('Recording')) {
                obj['Recording'] = Recording.constructFromObject(data['Recording']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecordingStateParameter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecordingStateParameter</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Recording`
        if (data['Recording']) { // data not null
          Recording.validateJSON(data['Recording']);
        }

        return true;
    }


}





export default RecordingStateParameter;

