/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The VREvent model module.
 * @module model/VREvent
 * @version v0
 */
export class VREvent {
    /**
     * Constructs a new <code>VREvent</code>.
     * @alias VREvent
     */
    constructor() { 
        
        
        /** object 
         * @type {Object.<String, String>} 
         */
        this.object = undefined;

        /** changes 
         * @type {Object.<String, Object>} 
         */
        this.changes = undefined;

        /** timestamp 
         * @type {Date} 
         */
        this.timestamp = undefined;
        
        
        
        
        VREvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VREvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {VREvent} obj Optional instance to populate.
     * @return {VREvent} The populated <code>VREvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VREvent();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], {'String': 'String'});
            }
            if (data.hasOwnProperty('changes')) {
                obj['changes'] = ApiClient.convertToType(data['changes'], {'String': Object});
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VREvent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VREvent</code>.
     */
    static validateJSON(data) {

        return true;
    }


}





export default VREvent;

